# Generated by Django 4.1.6 on 2024-08-17 16:22

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.CharField(db_column='ImageUrl', max_length=500)),
                ('carid', models.CharField(blank=True, db_column='CarId', max_length=30, null=True)),
                ('uploaded_date', models.DateTimeField(db_column='UploadedDate', default=django.utils.timezone.now)),
                ('processed_date', models.DateTimeField(blank=True, db_column='ProcessedDate', null=True)),
                ('uploader_username', autoslug.fields.AutoSlugField(editable=False, populate_from='uploader')),
                ('car_model', models.CharField(blank=True, db_column='CarModel', max_length=255, null=True)),
                ('model_description', models.TextField(blank=True, db_column='ModelDescription', max_length=700, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProcessedImageDetail',
            },
        ),
    ]
